# Site settings
title: Artificial Intelligence and Statistics Conference
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS 2025 conference.
baseurl: "/aistats2025/" # the subpath of your site, e.g. /blog/
timezone: ICT

repository: aistats/aistats2025

# If you want to create a twitter account for your conference include
# twitter name here
twitter_username: aistats_conf

github_username:  aistats

author:
  name: AISTATS
  # You might want to create an email for handling conference queries, e.g. aistats2025@gmail.com. If you do, you can enter it here.
  email: aistats2025conference@gmail.com
comments: false

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# change encoding for the generated output files to utf-8
encoding: utf-8
remote_theme: aistats/jekyll-theme
style: aistats

ghub:
  edit: true
  repository: aistats2025

# Place a banner image in assets/images and give its name here.
# TODO: attribute creator of image: https://commons.wikimedia.org/wiki/File:Arrival_to_airport_Phuket_11_feb%272013_-_panoramio.jpg
banner: mai-khao.png
banner_title: Artificial Intelligence and Statistics 2025

conference:
  full_name: Artificial Intelligence and Statistics
  short_name: AISTATS
  name: Artificial Intelligence and Statistics
  # set to True if the programme is draft only.
  draft: true
  # set to True to hide tentative speakers
  hide_tentative: true
  # Place an image of venue in assets/images and give its name here
  image: mai-khao.png
  proceedings:
    # When proceedings are published add url here.
    url:
    show: false
  # Give details of the room in the venue here.
  room:
  # Set the name of the venue (e.g. Caribe Hilton Hotel)
  venue: Splash Beach Resort
  # Give the url of the venue here.
  venue_url:
  # Give the conference location in the form City, Country here.
  location: Mai Khao, Thailand
  year: 2025
  # Give the instance of the conference here (e.g. 24th)
  instance: 28th
  # Styling for AISTATS is "International Conference"
  styling: International Conference on
  # Give the individual days that the conference will be held on here.
  dates:
  - 3 May 2025
  - 4 May 2025
  - 5 May 2025
  # Give the submission site details here.
  submission:
    # Whether to show the submission site.
    show: false
    # The URL of the submission site.
    url: "https://openreview.net/group?id=aistats.org/AISTATS/2025/Conference"
    # The name of the submission site (e.g. Microsoft CMT Website)
    name:
  deadlines:
    # Fill in the key dates as below.
    # - name: Submission server open
    #   type: submission
    #   date: TBA
    - name: Abstract submission deadline
      type: submission
      date: 3 October 2024
    - name: Paper submission deadline
      type: submission
      date: 10 October 2024
    - name: Appendix submission deadline
      type: submission
      date: 17 October 2024
    - name: Reviews released
      date: 27 November 2024
    - name: Author rebuttals due
      type: submission
      date: 5 December 2024
    - name: Paper decision notifications
      type: decision
      date: 21 January 2025
    # - name: Early Registration deadline
    #   text: 27 March 2025 (01:00 AM UTC)
    #   date: 27 March 2025
  # List program chairs here.
  chairs:
  # If there's a local chair, or a general chair, you can add them here.
  - type: General Chair
    people:
    - family: Li
      given: Yingzhen
      url: "http://yingzhenli.net/"
      institute: Imperial College London, London, UK
    - family: Mandt
      given: Stephan
      url: "https://www.stephanmandt.com/"
      institute: University of California, Irvine, USA
  - type: Program Chair
    people:
    - family: Agrawal
      given: Shipra
      url: "https://www.columbia.edu/~sa3305/"
      institute: Columbia University, New York, USA
    - family: Khan
      given: Emtiyaz
      # Give their personal web page.
      url: "https://emtiyaz.github.io/"
      institute: RIKEN, Tokyo, Japan
  # You might want Workflow Chair(s) to assist with your submission system and the review process.
  - type: Workflow Chair
    people:
    - family: Anders
      given: Christopher J.
      url: "https://cjanders.de"
      institute: RIKEN, Tokyo, Japan
    - family: Ou
      given: Tingting
      url: "https://ieor.columbia.edu/content/tingting-ou"
      institute: Columbia University, New York, USA
  # Your Publication Chair handles processing of proceedings.
  # - type: Publication Chair
  #   people:
  #   - family:
  #     given:
  #     url:
  #     institute:
  # Publicity Chairs often handle websites, social media etc.
  # - type: Publicity Chair
  #   people:
  #   - family:
  #     given:
  #     url:
  #     institute:
  # D&I Chairs look after initiatives to ensure an inclusive conference
  - type: D&I Chair
    people:
    - family: Khetarpal
      given: Khimya
      url: "https://kkhetarpal.github.io/"
      institute: Google DeepMind
  # Sponsorship chairs handle bringing in money from sponsors.
  - type: Sponsorship Chair
    people:
    - family: Fortuin
      given: Vincent
      url: "https://fortuin.github.io/"
      institute: Helmholtz AI, Munich, Germany
  - type: Local Chair
    people:
    - family: Maundet
      given: Krikamol
      url: "http://www.krikamol.org"
      institute: CISPA Helmholtz Center for Information Security, Saarbrücken, Germany
    - family: Krityakierne
      given: Tipaluck
      url: "https://sites.google.com/a/cornell.edu/tipaluck/home"
      institute: Mahidol University, Salaya, Thailand
  - type: Publication Chair
    people:
    - family: Burroni
      given: Javier
      url: https://jburroni.github.io/
      institute: University of Massachusetts, Amherst, USA
