# Site settings
title: Artificial Intelligence and Statistics Conference
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS 2025 conference.
baseurl: "" # the subpath of your site, e.g. /blog/
timezone: ICT

# If you want to create a twitter account for your conference include
# twitter name here
twitter_username: aistats_conf

github_username:  aistats

author:
  name: AISTATS
  # You might want to create an email for handling conference queries, e.g. aistats2025@gmail.com. If you do, you can enter it here.
  email:
comments: false

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# change encoding for the generated output files to utf-8
encoding: utf-8
remote_theme: aistats/jekyll-theme
style: aistats

ghub:
  edit: true
  repository: aistats2025

# Place a banner image in assets/images and give its name here.
# TODO: attribute creator of image: https://commons.wikimedia.org/wiki/File:Arrival_to_airport_Phuket_11_feb%272013_-_panoramio.jpg
banner: mai-khao.png
banner_title: Artificial Intelligence and Statistics 2025

conference:
  full_name: Artificial Intelligence and Statistics
  short_name: AISTATS
  name: Artificial Intelligence and Statistics
  # set to True if the programme is draft only.
  draft: true
  # set to True to hide tentative speakers
  hide_tentative: true
  # Place an image of venue in assets/images and give its name here
  image: mai-khao.png
  proceedings:
    # When proceedings are published add url here.
    url:
    show: false
  # Give details of the room in the venue here.
  room:
  # Set the name of the venue (e.g. Caribe Hilton Hotel)
  venue: Splash Beach Resort
  # Give the url of the venue here.
  venue_url:
  # Give the conference location in the form City, Country here.
  location: Mai Khao, Thailand
  year: 2025
  # Give the instance of the conference here (e.g. 24th)
  instance: 28th
  # Styling for AISTATS is "International Conference"
  styling: International Conference on
  # Give the individual days that the conference will be held on here.
  dates:
  - May 3 2025
  - May 4 2025
  - May 5 2025
  # Give the submission site details here.
  submission:
    # Whether to show the submission site.
    show: false
    # The URL of the submission site.
    url:
    # The name of the submission site (e.g. Microsoft CMT Website)
    name:
  deadlines:
    # Fill in the key dates as below.
    - name: Submission server open
      type: submission
      date: TBA
    - name: Abstract submission deadline
      type: submission
      time: TBA
    - name: Paper submission deadline
      type: submission
      time: TBA
    - name: Appendix submission deadline
      type: submission
      time: TBA
    - name: Reviews released
      date: TBA
    - name: Author rebuttals due
      type: submission
      time: TBA
    - name: Paper decision notifications
      type: decision
      date: TBA
    - name: Early Registration deadline
      date: TBA
  # List program chairs here.
  chairs:
  - type: Program Chairs
    people:
    - family: Agrawal
      given: Shipra
      url: "https://www.columbia.edu/~sa3305/"
      institute: Columbia University
    - family: Khan
      given: Emtiyaz
      # Give their personal web page.
      url: "https://emtiyaz.github.io/"
      institute: RIKEN
  # If there's a local chair, or a general chair, you can add them here.
  # - type: General Chair
  #   people:
  #   - family:
  #     given:
  #     url:
  #     institute:
  # You might want Workflow Chair(s) to assist with your submission system and the review process.
  - type: Workflow Chairs
    people:
    - family: Anders
      given: Christopher
      url:
      institute: RIKEN
    - family: Ou
      given: Tingting
      url:
      institute: Columbia University
  # Your Publication Chair handles processing of proceedings.
  # - type: Publication Chair
  #   people:
  #   - family:
  #     given:
  #     url:
  #     institute:
  # Publicity Chairs often handle websites, social media etc.
  # - type: Publicity Chair
  #   people:
  #   - family:
  #     given:
  #     url:
  #     institute:
  # D&I Chairs look after initiatives to ensure an inclusive conference
  # - type: D&I Chair
  #   people:
  #   - family:
  #     given:
  #     url:
  #     institute:
  # Sponsorship chairs handle bringing in money from sponsors.
  # - type: Sponsorship Chair
  #   people:
  #   - family:
  #     given:
  #     url:
  #     institute:
  # - type: Local Chair
  #   people:
  #   - family:
  #     given:
  #     url:
  #     institute:
